backend = "glx";
glx-no-stencil = true;
glx-copy-from-front = false;
glx-swap-method = 2;

vsync = true;
use-damage = true;

# Opacity
active-opacity = 1;
inactive-opacity = 1;
frame-opacity = 1;
inactive-opacity-override = false;

blur-background = true;
blur-method = "dual_kawase";
blur-strength = 6;

# Fading
fading = true;
fade-delta = 4;
no-fading-openclose = false;
fade-exclude = [
    "class_g = 'Horizon-client'"
];

# Window type settings
wintypes:
{
    dock = {
        shadow = false;
    };
};

opacity-rule = [
    "100:class_g = 'Horizon-client'",
    "85:class_g = 'obsidian' && focused",
    "60:class_g = 'obsidian' && !focused",
    "85:class_g = 'kitty' && focused",
    "45:class_g = 'kitty' && !focused"
];

xrender-sync-fence = true;

# Corners
corner-radius = 20.0;
rounded-corners-exclude = [
    "class_g = 'Horizon-client'"
];
round-borders = 1;
round-borders-exclude = [];

# Horizon-client exclusions
blur-background-exclude = [
    "class_g = 'Horizon-client'"
];

shadow-exclude = [
    "class_g = 'Horizon-client'"
];

focus-exclude = [
    "class_g = 'Horizon-client'"
];

unredir-if-possible-exclude = [
    "class_g = 'Horizon-client'"
];

damage-exclude = [
    "class_g = 'Horizon-client'"
];

transparent-clipping-exclude = [
    "class_g = 'Horizon-client'"
];
