preload = ~/.config/hypr/wallpapers/bluespace.jpg
preload = ~/.config/hypr/wallpapers/newscreen.jpg
preload = ~/.config/hypr/wallpapers/pxfuel.jpg

wallpaper = DP-1,~/.config/hypr/wallpapers/bluespace.jpg
wallpaper = DP-2,~/.config/hypr/wallpapers/newscreen.jpg
wallpaper = DP-3,~/.config/hypr/wallpapers/pxfuel.jpg

splash = false
